#!/bin/zsh

killall transmission-daemon 2> /dev/null
start() { 
    transmission-daemon -g ~/.config/transmission-daemon --foreground --log-info 2>&1 | while read line; do
    echo $line |
	    grep -v "announcer.c:\|platform.c:\|announce done (tr-dht.c:" |
		grep -v "Saved.*variant.c:" |
		while read line; do
			echo $line | grep -q "Queued for verification (verify.c:" &&
				notify-send --app-name="Transmission Started" "${line#* * }"
			echo $line | grep -q "changed from .Incomplete. to .Complete." &&
				notify-send --app-name="Transmission Complete" "${line#* * }"
			echo $line | systemd-cat --identifier="TransWrap" --priority=5
        done 2>&1 > /dev/null
    done&disown
}

essid=$(iwgetid wlp5s0 | gawk '{print gensub(/.*ESSID:\"(.+)\"/, "\\1", 1)}')
if [ $essid = 'judas' ]; then start; fi
