#!/usr/bin/env zsh

sleep 5
trayer --edge top --distance 16 --align left --margin 200 --SetDockType true \
       --SetPartialStrut true --widthtype request --transparent true \
       --tint 0x263238 --alpha 0 --height 12 &
